# Generated by Django 4.0 on 2023-08-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePaciente', models.CharField(blank=True, max_length=255)),
                ('sobrenome', models.CharField(blank=True, max_length=255)),
                ('nomeclinica', models.CharField(blank=True, max_length=255)),
                ('sexo', models.CharField(max_length=2)),
                ('idadepaciente', models.CharField(max_length=3)),
                ('temcancer', models.CharField(max_length=3)),
                ('cancer_mama', models.CharField(max_length=25)),
                ('idade_diagnostico', models.CharField(max_length=25)),
                ('mutacaoGenetica', models.CharField(max_length=22)),
                ('opc_bilateral', models.CharField(max_length=3)),
                ('opc_ovario', models.CharField(max_length=3)),
                ('tipo_molecular', models.CharField(max_length=23)),
                ('tam_cancer', models.CharField(max_length=23)),
                ('historicoFMasculino', models.CharField(max_length=23)),
                ('qtd_parent_2', models.CharField(max_length=12)),
                ('parent_seg_grau', models.CharField(max_length=12)),
                ('parent_pri_grau', models.CharField(max_length=25)),
                ('asc_judia', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('titulo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('peso', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('mostrar', models.BooleanField(default=True)),
            ],
        ),
    ]
