# Generated by Django 4.0 on 2023-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('titulo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('peso', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('mostrar', models.BooleanField(default=True)),
            ],
        ),
    ]
