# Generated by Django 4.0 on 2023-08-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
