# Generated by Django 4.0 on 2023-08-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cancer_mama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='historicoFMasculino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='mutacaoGenetica',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='parent_pri_grau',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tam_cancer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='temcancer',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipo_molecular',
            field=models.CharField(max_length=100),
        ),
    ]
