# Generated by Django 4.0 on 2023-08-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='qtd_parent_1',
        ),
    ]
