# Generated by Django 4.0 on 2023-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_formulario_cancer_mama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='cancer_mama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='idade_diagnostico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='mutacaoGenetica',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='opc_bilateral',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='opc_ovario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='parent_seg_grau',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='qtd_parent_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='temcancer',
            field=models.CharField(max_length=100),
        ),
    ]
