# Generated by Django 4.0 on 2023-08-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formulario_cancer_mama_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='tam_cancer',
        ),
    ]
