# Generated by Django 3.2.5 on 2023-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_formulario_temcancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionarPerguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo da Pergunta')),
                ('tipo', models.CharField(blank=True, choices=[('Select', 'Select'), ('Texto', 'Texto')], max_length=10, verbose_name='Tipo da pergunta:')),
            ],
        ),
    ]
