# Generated by Django 3.2.5 on 2023-08-05 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_adicionarperguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nova_pergunta',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='forms.adicionarperguntas'),
        ),
    ]
