# Generated by Django 3.2.5 on 2023-08-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_formulario_nova_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='nova_pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.adicionarperguntas'),
        ),
    ]
