# Generated by Django 3.2.5 on 2023-08-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_remove_adicionarperguntas_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='nova_pergunta',
        ),
        migrations.DeleteModel(
            name='AdicionarPerguntas',
        ),
    ]
