# Generated by Django 3.2.5 on 2023-04-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePaciente', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('nomeclinica', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Feminino'), ('F', 'Matutino')], max_length=2, verbose_name='Sexo')),
                ('idadepaciente', models.CharField(max_length=3)),
                ('mutacaoGenetica', models.CharField(choices=[('1', 'BRCA1'), ('2', 'BRCA2'), ('3', 'TP54'), ('4', 'CDH1'), ('5', 'STK11'), ('6', 'PTEN'), ('7', 'PALB2'), ('8', 'VUS')], max_length=1, verbose_name='Teste genético apresenta mutação do tipo:')),
                ('opc_bilateral', models.CharField(choices=[('1', 'SIM'), ('2', 'NAO')], max_length=1, verbose_name='Historico Pessoal de cancer de mama bilateral:')),
                ('opc_ovario', models.CharField(choices=[('1', 'SIM'), ('2', 'NAO')], max_length=1, verbose_name='Tem historico Pessoal de cançer de ovario?')),
                ('temcancer', models.CharField(choices=[('1', 'SIM'), ('2', 'NAO')], max_length=2, verbose_name='Tem câncer de mama?')),
                ('cancer_mama', models.CharField(choices=[('1', 'Carcinoma ductal insitu'), ('2', 'Carcinoma não epecial'), ('3', 'Lobural'), ('4', 'Medular'), ('5', 'Metaplatico'), ('6', 'Mucinoso')], max_length=2, verbose_name='Se tem câncer de mama, qual tipo histologico?')),
                ('idade_diagnostico', models.CharField(choices=[('1', 'Maior que 60 anos'), ('2', 'Entre 55 e 60 anos'), ('3', 'Entre 45 e 55 anos'), ('4', 'Entre 35 e 45 anos'), ('5', 'Entre 30 e 35 anos'), ('6', 'Menor que 30 anos')], max_length=2, verbose_name='Faixa de idade do diagnostico de câncer de mama:')),
                ('tipo_molecular', models.CharField(choices=[('1', 'Lumial'), ('2', 'Lumial HEr2'), ('3', 'HEr2'), ('4', 'Triplo Negativo')], max_length=2, verbose_name=' Tipo molecular de câncer de mama:')),
                ('tam_cancer', models.CharField(choices=[('1', 'Insitu'), ('2', 'T1'), ('3', 'T2'), ('4', 'T3'), ('5', 'T4')], max_length=2, verbose_name='Se tem câncer, qual o tamanho do tumor:')),
                ('qtd_parent_1', models.CharField(choices=[('1', 'Um'), ('2', 'Dois'), ('3', 'Três ou Mais'), ('4', 'Desconhece')], max_length=2, verbose_name='Quantidade parentes de primeiro grau com câncer de mama:')),
                ('qtd_parent_2', models.CharField(choices=[('1', 'Um'), ('2', 'Dois'), ('3', 'Três ou Mais'), ('4', 'Desconhece')], max_length=2, verbose_name='Quantidade de parentes de segundo grau ou mais distante com câncer de mama ou ovario < 50 anos:')),
                ('parent_seg_grau', models.CharField(choices=[('1', 'Um'), ('2', 'Dois'), ('3', 'Três ou Mais'), ('4', 'Desconhece')], max_length=2, verbose_name=' Parentes de segundo grau ou mais distante com câncer de mama ou ovario < 50 anos:')),
                ('parent_pri_grau', models.CharField(choices=[('1', 'Um'), ('2', 'Dois'), ('3', 'Três ou Mais'), ('4', 'Desconhece')], max_length=2, verbose_name='Parentes de primeiro grau com :')),
                ('asc_judia', models.CharField(choices=[('1', 'SIM'), ('2', 'NAO')], max_length=2, verbose_name='Ascendencia Judia Ashkenazi:')),
            ],
        ),
    ]
