# Generated by Django 3.2.5 on 2023-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePaciente', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('nomeclinica', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('M', 'Feminino'), ('F', 'Matutino')], max_length=2, verbose_name='Sexo')),
                ('idadepaciente', models.CharField(max_length=3)),
                ('mutacaoGenetica', models.CharField(max_length=25)),
                ('opc_bilateral', models.CharField(max_length=25)),
                ('opc_ovario', models.CharField(max_length=25)),
                ('cancer_mama', models.CharField(max_length=25)),
                ('cancer_diagnostico', models.CharField(max_length=25)),
                ('cancer_histologico', models.CharField(max_length=25)),
                ('tipo_molecular', models.CharField(max_length=25)),
                ('tam_cancer', models.CharField(max_length=25)),
                ('qtd_parent_1', models.CharField(max_length=25)),
                ('qtd_parent_2', models.CharField(max_length=25)),
                ('parent_seg_grau', models.CharField(max_length=25)),
                ('parent_pri_grau', models.CharField(max_length=25)),
                ('asc_judia', models.CharField(max_length=25)),
            ],
        ),
    ]
