# Generated by Django 3.2.5 on 2023-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='nomePaciente',
            field=models.CharField(max_length=255, verbose_name='Nome do paciente:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='nomeclinica',
            field=models.CharField(max_length=255, verbose_name='Nome da clinica:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sobrenome',
            field=models.CharField(max_length=255, verbose_name='Sobrenome:'),
        ),
    ]
