# Generated by Django 3.2.5 on 2023-04-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutacaoGenetica', models.CharField(max_length=3)),
                ('opc_bilateral', models.CharField(max_length=3)),
                ('opc_ovario', models.CharField(max_length=3)),
                ('cancer_mama', models.CharField(max_length=3)),
                ('cancer_diagnostico', models.CharField(max_length=3)),
                ('cancer_histologico', models.CharField(max_length=3)),
                ('tipo_molecular', models.CharField(max_length=3)),
                ('tam_cancer', models.CharField(max_length=3)),
                ('qtd_parent_1', models.CharField(max_length=3)),
                ('qtd_parent_2', models.CharField(max_length=3)),
                ('parent_seg_grau', models.CharField(max_length=3)),
                ('parent_pri_grau', models.CharField(max_length=3)),
                ('asc_judia', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedoPaciente', models.CharField(max_length=255)),
                ('sobreNome', models.CharField(max_length=255)),
                ('nomeClinica', models.CharField(max_length=255)),
                ('idadePaciente', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
        migrations.AddField(
            model_name='form',
            name='dado_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forms.paciente'),
        ),
    ]
