# Generated by Django 4.1.6 on 2023-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('peso', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Perguntas',
        ),
    ]
