# Generated by Django 3.2.5 on 2023-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='temcancer',
            field=models.BooleanField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Tem câncer de mama?'),
        ),
    ]
