# Generated by Django 3.2.5 on 2023-04-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20230413_0153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Forms',
        ),
    ]
