# Generated by Django 3.2.5 on 2023-04-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_form_forms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='Form',
        ),
    ]
