# Generated by Django 3.2.5 on 2023-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_form_idadepaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='sexo',
            field=models.CharField(choices=[('M', 'Feminino'), ('F', 'Masculino')], max_length=2, verbose_name='Sexo'),
        ),
    ]
