# Generated by Django 4.1.6 on 2023-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_form_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='nomePaciente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do paciente:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='nomeclinica',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome da clinica:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sobrenome:'),
        ),
    ]
