# Generated by Django 3.2.5 on 2023-04-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_forms_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='asc_judia',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='cancer_diagnostico',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='cancer_histologico',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='cancer_mama',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='mutacaoGenetica',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_bilateral',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_ovario',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent_pri_grau',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent_seg_grau',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='qtd_parent_1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='qtd_parent_2',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='tam_cancer',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='form',
            name='tipo_molecular',
            field=models.CharField(max_length=5),
        ),
    ]
