# Generated by Django 3.2.5 on 2023-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_form_nomepaciente_alter_form_nomeclinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
