# Generated by Django 3.2.5 on 2023-05-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_form_mostrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='mostrar',
        ),
        migrations.AlterField(
            model_name='form',
            name='asc_judia',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=12, verbose_name='Ascendencia Judia Ashkenazi:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='cancer_mama',
            field=models.CharField(choices=[('Carcinoma ductal insitu', 'Carcinoma ductal insitu'), ('Carcinoma não epecial', 'Carcinoma não epecial'), ('Lobural', 'Lobural'), ('Medular', 'Medular'), ('Metaplatico', 'Metaplatico'), ('Mucinoso', 'Mucinoso')], max_length=25, verbose_name='Se tem câncer de mama, qual tipo histologico?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='idade_diagnostico',
            field=models.CharField(choices=[('Maior que 60 anos', 'Maior que 60 anos'), ('Entre 55 e 60 anos', 'Entre 55 e 60 anos'), ('Entre 45 e 55 anos', 'Entre 45 e 55 anos'), ('Entre 35 e 45 anos', 'Entre 35 e 45 anos'), ('Entre 30 e 35 anos', 'Entre 30 e 35 anos'), ('Menor que 30 anos', 'Menor que 30 anos')], max_length=25, verbose_name='Faixa de idade do diagnostico de câncer de mama:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='mutacaoGenetica',
            field=models.CharField(choices=[('BRCA1', 'BRCA1'), ('BRCA2', 'BRCA2'), ('TP54', 'TP54'), ('CDH1', 'CDH1'), ('STK11', 'STK11'), ('PTEN', 'PTEN'), ('PALB2', 'PALB2'), ('VUS', 'VUS')], max_length=5, verbose_name='Teste genético apresenta mutação do tipo:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_bilateral',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Historico Pessoal de cancer de mama bilateral:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_ovario',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Tem historico Pessoal de cançer de ovario?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent_pri_grau',
            field=models.CharField(choices=[('Um', 'Um'), ('Dois', 'Dois'), ('Três ou Mais', 'Três ou Mais'), ('Desconhece', 'Desconhece')], max_length=12, verbose_name='Parentes de primeiro grau com :'),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent_seg_grau',
            field=models.CharField(choices=[('Um', 'Um'), ('Dois', 'Dois'), ('Três ou Mais', 'Três ou Mais'), ('Desconhece', 'Desconhece')], max_length=12, verbose_name=' Parentes de segundo grau ou mais distante com câncer de mama ou ovario < 50 anos:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='qtd_parent_1',
            field=models.CharField(choices=[('Um', 'Um'), ('Dois', 'Dois'), ('Três ou Mais', 'Três ou Mais'), ('Desconhece', 'Desconhece')], max_length=12, verbose_name='Quantidade parentes de primeiro grau com câncer de mama:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='qtd_parent_2',
            field=models.CharField(choices=[('Um', 'Um'), ('Dois', 'Dois'), ('Três ou Mais', 'Três ou Mais'), ('Desconhece', 'Desconhece')], max_length=12, verbose_name='Quantidade de parentes de segundo grau ou mais distante com câncer de mama ou ovario < 50 anos:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tam_cancer',
            field=models.CharField(choices=[('Insitu', 'Insitu'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4')], max_length=7, verbose_name='Se tem câncer, qual o tamanho do tumor:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='temcancer',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Tem câncer de mama?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tipo_molecular',
            field=models.CharField(choices=[('Lumial', 'Lumial'), ('Lumial HEr2', 'Lumial HEr2'), ('HEr2', 'HEr2'), ('Triplo Negativo', 'Triplo Negativo')], max_length=16, verbose_name=' Tipo molecular de câncer de mama:'),
        ),
    ]
