# Generated by Django 3.2.5 on 2023-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20230520_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='asc_judia',
            field=models.BooleanField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=12, verbose_name='Ascendencia Judia Ashkenazi:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_bilateral',
            field=models.BooleanField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Historico Pessoal de cancer de mama bilateral:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_ovario',
            field=models.BooleanField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Tem historico Pessoal de cançer de ovario?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent_pri_grau',
            field=models.CharField(choices=[('Cancer de ovario', 'Cancer de ovario'), ('Cancer de mama masculino', 'Cancer de mama masculino'), ('Cancer de prostata', 'Cancer de prostata'), ('Cancer bilateral de mama', 'Cancer bilateral de mama'), ('Cancer de pancreas', 'Cancer de pancreas'), ('Dois ou mais itens', 'Dois ou mais itens'), ('Nenhum', 'Nenhum'), ('Desconhce', 'Desconhece')], max_length=25, verbose_name='Parentes de primeiro grau com :'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=2, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='form',
            name='temcancer',
            field=models.BooleanField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Tem câncer de mama?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tipo_molecular',
            field=models.CharField(choices=[('Lumial', 'Lumial'), ('Lumial HEr2', 'Lumial HEr2'), ('HEr2', 'HEr2'), ('Triplo Negativo', 'Triplo Negativo')], max_length=16, verbose_name='Tipo molecular de câncer de mama:'),
        ),
    ]
