# Generated by Django 3.2.5 on 2023-05-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20230530_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='asc_judia',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=12, verbose_name='Ascendencia Judia Ashkenazi:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_bilateral',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Historico Pessoal de cancer de mama bilateral:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='opc_ovario',
            field=models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=3, verbose_name='Tem historico Pessoal de cançer de ovario?'),
        ),
    ]
