# Generated by Django 3.2.5 on 2023-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_form_temcancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='mutacaoGenetica',
            field=models.CharField(choices=[('BRCA1', 'BRCA1'), ('BRCA2', 'BRCA2'), ('TP53', 'TP54'), ('CDH1', 'CDH1'), ('STK11', 'STK11'), ('PTEN', 'PTEN'), ('PALB2', 'PALB2'), ('VUS', 'VUS'), ('NÃO APRESENTA MUTAÇÃO', 'NÃO APRESENTA MUTAÇÃO')], max_length=22, verbose_name='Teste genético apresenta mutação do tipo:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tipo_molecular',
            field=models.CharField(choices=[('Luminal', 'Luminal'), ('Luminal HEr2', 'Luminal HEr2'), ('HEr2', 'HEr2'), ('Triplo Negativo', 'Triplo Negativo')], max_length=16, verbose_name='Tipo molecular de câncer de mama:'),
        ),
    ]
