# Generated by Django 3.2.5 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20230530_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='cancer_mama',
            field=models.CharField(choices=[('Carcinoma ductal insitu', 'Carcinoma ductal insitu'), ('Carcinoma não epecial', 'Carcinoma não epecial'), ('Lobural', 'Lobural'), ('Medular', 'Medular'), ('Metaplatico', 'Metaplatico'), ('Mucinoso', 'Mucinoso'), ('Não tem cancer de mama', 'Não tem cancer de mama')], max_length=25, verbose_name='Se tem câncer de mama, qual tipo histologico?'),
        ),
        migrations.AlterField(
            model_name='form',
            name='mutacaoGenetica',
            field=models.CharField(choices=[('BRCA1', 'BRCA1'), ('BRCA2', 'BRCA2'), ('TP53', 'TP53'), ('CDH1', 'CDH1'), ('STK11', 'STK11'), ('PTEN', 'PTEN'), ('PALB2', 'PALB2'), ('VUS', 'VUS'), ('NÃO APRESENTA MUTAÇÃO', 'NÃO APRESENTA MUTAÇÃO')], max_length=22, verbose_name='Teste genético apresenta mutação do tipo:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tam_cancer',
            field=models.CharField(choices=[('Insitu', 'Insitu'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('Não tem cancer de mama', 'Não tem cancer de mama')], max_length=23, verbose_name='Se tem câncer, qual o tamanho do tumor:'),
        ),
        migrations.AlterField(
            model_name='form',
            name='tipo_molecular',
            field=models.CharField(choices=[('Luminal', 'Luminal'), ('Luminal HEr2', 'Luminal HEr2'), ('HEr2', 'HEr2'), ('Triplo Negativo', 'Triplo Negativo'), ('Não tem cancer de mama', 'Não tem cancer de mama')], max_length=23, verbose_name='Tipo molecular de câncer de mama:'),
        ),
    ]
